### ISSUE TITLE
Lossless soundtrack download from Jagex's servers is unstable and fails often

### ISSUE THREAD

**Issue by computeteen5** [villermen/runescape-cache-tools#51] opened 2017-05-01 22:28 UTC
Upon running the following command, the output terminates in failure either immediately or a random interval into the download.
.\rsct.exe -d -o=C:\Extract1 -s --lossless
[17:25:04 INFO DownloaderCache] Requested connection used outdated version 878. Retrying with higher major version.
[17:25:06 INFO DownloaderCache] Requested connection used outdated version 879. Retrying with higher major version.
System.TimeoutException: The file request was not fulfilled within 10 seconds.
   at Villermen.RuneScapeCacheTools.Cache.Downloader.FileRequest.WaitForCompletion()
   at Villermen.RuneScapeCacheTools.Cache.Downloader.DownloaderCache.FetchFile(Index index, Int32 fileId)
   at Villermen.RuneScapeCacheTools.Cache.CacheBase.GetFile(Index index, Int32 fileId, Int32 entryId)
   at Villermen.RuneScapeCacheTools.Cache.CacheBase.GetFile[T](Index index, Int32 fileId, Int32 entryId)
   at Villermen.RuneScapeCacheTools.Cache.Downloader.DownloaderCache.<>c__DisplayClass74_0.<GetReferenceTable>b__0(Index index2)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Villermen.RuneScapeCacheTools.Cache.Downloader.DownloaderCache.GetReferenceTable(Index index)
   at Villermen.RuneScapeCacheTools.Cache.Downloader.DownloaderCache.FetchFile(Index index, Int32 fileId)
   at Villermen.RuneScapeCacheTools.Cache.CacheBase.GetFile(Index index, Int32 fileId, Int32 entryId)
   at Villermen.RuneScapeCacheTools.Cache.CacheBase.GetFile[T](Index index, Int32 fileId, Int32 entryId)
   at Villermen.RuneScapeCacheTools.Audio.Soundtrack.GetTrackNames(Boolean includeUnnamed)
   at Villermen.RuneScapeCacheTools.Audio.Soundtrack.Extract(Boolean overwriteExisting, Boolean lossless, Boolean includeUnnamed, String[] nameFilters)
   at Villermen.RuneScapeCacheTools.CLI.Program.CombineSoundtrack()
   at Villermen.RuneScapeCacheTools.CLI.Program.Main(String[] args)

**Comment by villermen** [comment] 2017-05-01 22:43
I've noticed this today as well. It hasn't done this before and it's likely
caused by the same reason people have been randomly disconnecting as of
late.

Regardless I should build in a retry-mechanic that will retry the file
download/connection in case of failure.

**Comment by villermen** [comment] 2017-05-02 19:58
I will continue this in #53, but will close this issue after I can verify that it is fixed.

**Comment by villermen** [comment] 2017-05-03 09:47
The [latest release](https://github.com/villermen/runescape-cache-tools/releases/tag/v3.0.4) will probably fix your issue by waiting indefinitely, but will still not work in case of connection failures. Please try it and see if it solved your problem.

**Comment by computeteen5** [comment] 2017-05-03 09:57
Yes, this seems to fix the issue. I suppose if the downloading and assembly process took longer than 10 seconds per track before it would error out, but now it's fine.

**Comment by villermen** [comment] 2017-05-03 10:43
The requests were stacking up so much that the responses couldn't be read in the 10 seconds available for each request. (We're talking about several hundreds of files requested at the same time). I just disabled the time limit, but in #53 I'll implement a limit to the amount of requests instead.

Glad to hear the issue has been resolved for you.

**Closed by villermen** 2017-05-03 10:43 UTC
